### ISSUE TITLE
"make all" failed

### ISSUE THREAD

**Issue by ziang87** [pulp-platform/pulp#22]
Hi,I am a student from China,and I am quite interested in pulp platform.I followed the steps in website.(https://github.com/pulp-platform)
However,when I followed the process of how to build SDK,an error occured when I enter "make all"

SDK build
You can then build the SDK with this command:

$ make all

root@cp1-VirtualBox:~/pulp-sdk# make all
git submodule update --init
source init.sh && ./pulp-tools/bin/plpbuild --p sdk checkout build env --stdout
Configuring Pulp project at /home/cp1/pulp-sdk
Traceback (most recent call last):
  File "./pulp-tools/bin/plpbuild", line 3, in <module>
    import plptools as plp
  File "/home/cp1/pulp-sdk/pulp-tools/bin/plptools.py", line 27, in <module>
    from plpobjects import *
  File "/home/cp1/pulp-sdk/pulp-tools/bin/plpobjects.py", line 32, in <module>
    from openpyxl import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1

I found someone who had a similar problem with me, but I don't think it was solved
https://pulp-platform.org/community/showthread.php?tid=146&highlight=make+all

Thank you very much in advance for your help.

**Comment by ziang87** [comment]
Makefile

SHELL=bash

MODULES ?= --p sdk

all: pulp-tools
        source init.sh && ./pulp-tools/bin/plpbuild $(MODULES) checkout build env --stdout

build: pulp-tools
        source init.sh && ./pulp-tools/bin/plpbuild $(MODULES) build --stdout

distclean: pulp-tools
        -source init.sh && ./pulp-tools/bin/plpbuild --p sdk distclean --stdout
        rm -rf build

clean: pulp-tools
        -source init.sh && ./pulp-tools/bin/plpbuild --p sdk distclean --stdout
        rm -rf build

env: pulp-tools
        source init.sh && ./pulp-tools/bin/plpbuild $(MODULES) env --stdout

deps: pulp-tools

**Comment by bluewww** [comment]
Ok I figured out what the issues is. You are running `python 3.5.x` which does not have f-strings (added in 3.6). `openpxyl`, the dependency which errors out (so we can blame them), started introducing f-strings in their code base here
https://bitbucket.org/openpyxl/openpyxl/commits/2a3f8fefa4bf5ec4ad894c5a0478e57866db1275 (Note the date 2019-11-12) which is justified since they dropped support for  < `python 3.6` here https://bitbucket.org/openpyxl/openpyxl/commits/2b0f42fd2a501905b40c0b434cbc6f16ff51fffe, much earlier.

You need to install an older version of `openpxyl` (like this `pip3 install openpyxl==2.6.4`).

`openpxy` defines a `python_requires` which indicates it's incompatbility with `python 3.5` so I don't know why it was installed. Maybe a bug in `pip`?
