### ISSUE TITLE
Bender Integration

### ISSUE THREAD

**Issue by OttG** [pulp-platform/pulp#58]
I had to revert the merge of Bender integration since I had not notice few tests not passing on the CI @micprog, please check the internal log and create a new PR with the fixes for those tests.

**Comment by micprog** [comment]
Sorry about this, I did not correctly interpret the CI results. I have fixed two of the three issues, the final failing test is due to an updated version of udma_i2c where I am not very familiar with the IP and changes, I have asked @adimauro-iis for some advice. Do you want me to open a PR to merge changes without this last fix, or rather wait for the fix?
