### ISSUE TITLE
L2_priv0 saturation

### ISSUE THREAD

**Issue by Alessandro0110** [pulp-platform/pulp#6]
Hello, thank you for your work. I am trying to run a program in which almost all data are stored in the L1 memory located in the cluster domain. In order to do this almost all variables are global and the statement RT_L1_DATA is used in their declaration. I have computed the quantity of data occupied by these variables and it is equal to almost 32KB (a little bit less). The other temporary variables declared during the execution of the program should occupy much lower space and I think that they are negligible in this computation.
The problem is the following:

![image](https://user-images.githubusercontent.com/41989472/53431980-f01f5e80-39f1-11e9-8dea-e99b5016d2e0.png)

Since the L1 memory is mainly used, I don't understand the reason why the problem is related to L2_priv0 that is a private FC memory bank. Anyone have an idea how to solve this problem?

Thank you in advance for the help.

**Comment by haugoug** [comment]
Since pulp chips always have the cluster powered down when the application binary is loaded, we put L1 initial values in L2, so that we can transfer them from L2 to L1 when the cluster is powered up during execution.
Although the open-source pulp always have the cluster powered-up, the runtime is still keeping L1 initial values in L2, which gets saturated in your case.
We will remove this feature soon for pulp. For now the only solution is for you is to patch this linker script: runtime/pulp-rt/rules/pulp/link.ld

**Comment by Alessandro0110** [comment]
I think that an other solutions could be the dynamic allocation by using the utility rt_alloc(RT_ALLOC_CL_DATA,...) in the cluster is it right?
I tried to modify the linker script but when I move the ORIGIN address of the L2_priv1 the result is the following:

#          26409859620: Illegal instruction (core 0) at PC 0x1c008080:

# Instruction is valid, but has at least one X

#          26410086948: Illegal instruction (core 0) at PC 0x1c008084:

# Instruction is valid, but has at least one X

Thank you in advance for the help.

**Comment by haugoug** [comment]
Yes going through dynamic allocation is a better solution
